# Generated by Django 2.1.7 on 2019-03-03 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(error_messages={'blank': 'Domain name cannot be blank.', 'max_length': 'Domain name cannot exceed 255 characters.', 'unique': 'Domain name must be unique.'}, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Not a valid domain name.', regex='^((?=[a-z0-9-]{1,63}\\.)[a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,63}$')])),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='registries.Registry')),
            ],
        ),
    ]
