# Generated by Django 2.1.7 on 2019-03-04 04:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hostname', models.CharField(error_messages={'blank': 'Hostname cannot be blank.', 'max_length': 'Hostname cannot exceed 63 characters.'}, max_length=63, validators=[django.core.validators.RegexValidator(message='Not a valid hostname.', regex='^[a-z0-9]+(-[a-z0-9]+)*$')])),
                ('address', models.GenericIPAddressField(protocol='IPv4', validators=[django.core.validators.validate_ipv4_address])),
                ('time_to_live', models.PositiveIntegerField(blank=True, default=None, help_text='Time in seconds for how long record should be cached by a resolver. If not set, inherited from domain.', null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_records', to='domains.Domain')),
            ],
        ),
    ]
