# Generated by Django 2.1.7 on 2019-03-02 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(error_messages={'blank': 'Registry name cannot be blank.', 'max_length': 'Registry name cannot exceed 120 characters.', 'unique': 'Registry name must be unique.'}, max_length=120, unique=True)),
            ],
        ),
    ]
